-- All sizes are in metres. "guess" says which size players guess.
-- "image" is empty until the silhouette is uploaded; then set it to "rbxassetid://<id>".
local ObjectLibrary = {}

ObjectLibrary.References = {
	{ id = "ref_bank_card", name = "Bank Card", guess = "length", height = 0.054, length = 0.0856, image = "", imageFile = "ref_bank_card.png" },
	{ id = "ref_a4_sheet", name = "A4 Sheet", guess = "height", height = 0.297, length = 0.21, image = "", imageFile = "ref_a4_sheet.png" },
	{ id = "ref_adult_person", name = "Adult Person", guess = "height", height = 1.7, length = 0.5, image = "", imageFile = "ref_adult_person.png" },
	{ id = "ref_door", name = "Door", guess = "height", height = 2, length = 0.9, image = "", imageFile = "ref_door.png" },
	{ id = "ref_car", name = "Car", guess = "length", height = 1.5, length = 4.5, image = "", imageFile = "ref_car.png" },
	{ id = "ref_school_bus", name = "School Bus", guess = "length", height = 3.2, length = 12, image = "", imageFile = "ref_school_bus.png" },
	{ id = "ref_statue_of_liberty", name = "Statue of Liberty", guess = "height", height = 93, length = 50, image = "", imageFile = "ref_statue_of_liberty.png" },
	{ id = "ref_eiffel_tower", name = "Eiffel Tower", guess = "height", height = 330, length = 125, image = "", imageFile = "ref_eiffel_tower.png" },
}

ObjectLibrary.Objects = {
	{ id = "pencil", name = "Pencil", category = "Everyday", guess = "length", height = 0.007, length = 0.19, difficulty = "easy", image = "", imageFile = "pencil.png" },
	{ id = "paperclip", name = "Paperclip", category = "Everyday", guess = "length", height = 0.008, length = 0.033, difficulty = "medium", image = "", imageFile = "paperclip.png" },
	{ id = "aa_battery", name = "AA Battery", category = "Everyday", guess = "length", height = 0.0145, length = 0.0505, difficulty = "medium", image = "", imageFile = "aa_battery.png" },
	{ id = "smartphone", name = "Smartphone", category = "Everyday", guess = "height", height = 0.147, length = 0.072, difficulty = "easy", image = "", imageFile = "smartphone.png" },
	{ id = "coffee_mug", name = "Coffee Mug", category = "Everyday", guess = "height", height = 0.095, length = 0.12, difficulty = "easy", image = "", imageFile = "coffee_mug.png" },
	{ id = "toothbrush", name = "Toothbrush", category = "Everyday", guess = "length", height = 0.02, length = 0.19, difficulty = "easy", image = "", imageFile = "toothbrush.png" },
	{ id = "tennis_ball", name = "Tennis Ball", category = "Everyday", guess = "height", height = 0.067, length = 0.067, difficulty = "medium", image = "", imageFile = "tennis_ball.png" },
	{ id = "basketball", name = "Basketball", category = "Everyday", guess = "height", height = 0.24, length = 0.24, difficulty = "easy", image = "", imageFile = "basketball.png" },
	{ id = "soccer_ball", name = "Soccer Ball", category = "Everyday", guess = "height", height = 0.22, length = 0.22, difficulty = "easy", image = "", imageFile = "soccer_ball.png" },
	{ id = "golf_ball", name = "Golf Ball", category = "Everyday", guess = "height", height = 0.043, length = 0.043, difficulty = "medium", image = "", imageFile = "golf_ball.png" },
	{ id = "acoustic_guitar", name = "Acoustic Guitar", category = "Everyday", guess = "length", height = 0.38, length = 1, difficulty = "medium", image = "", imageFile = "acoustic_guitar.png" },
	{ id = "violin", name = "Violin", category = "Everyday", guess = "length", height = 0.21, length = 0.59, difficulty = "medium", image = "", imageFile = "violin.png" },
	{ id = "grand_piano", name = "Grand Piano", category = "Everyday", guess = "length", height = 1, length = 2.74, difficulty = "hard", image = "", imageFile = "grand_piano.png" },
	{ id = "refrigerator", name = "Refrigerator", category = "Everyday", guess = "height", height = 1.8, length = 0.7, difficulty = "easy", image = "", imageFile = "refrigerator.png" },
	{ id = "washing_machine", name = "Washing Machine", category = "Everyday", guess = "height", height = 0.85, length = 0.6, difficulty = "easy", image = "", imageFile = "washing_machine.png" },
	{ id = "bicycle", name = "Bicycle", category = "Everyday", guess = "length", height = 1.05, length = 1.75, difficulty = "easy", image = "", imageFile = "bicycle.png" },
	{ id = "office_chair", name = "Office Chair", category = "Everyday", guess = "height", height = 1.1, length = 0.65, difficulty = "easy", image = "", imageFile = "office_chair.png" },
	{ id = "traffic_cone", name = "Traffic Cone", category = "Everyday", guess = "height", height = 0.7, length = 0.36, difficulty = "medium", image = "", imageFile = "traffic_cone.png" },
	{ id = "fire_hydrant", name = "Fire Hydrant", category = "Everyday", guess = "height", height = 0.75, length = 0.45, difficulty = "medium", image = "", imageFile = "fire_hydrant.png" },
	{ id = "lego_brick_2x4", name = "LEGO Brick 2x4", category = "Everyday", guess = "length", height = 0.0113, length = 0.032, difficulty = "hard", image = "", imageFile = "lego_brick_2x4.png" },
	{ id = "dice", name = "Dice", category = "Everyday", guess = "height", height = 0.016, length = 0.016, difficulty = "medium", image = "", imageFile = "dice.png" },
	{ id = "skateboard", name = "Skateboard", category = "Everyday", guess = "length", height = 0.1, length = 0.8, difficulty = "easy", image = "", imageFile = "skateboard.png" },
	{ id = "surfboard", name = "Surfboard", category = "Everyday", guess = "length", height = 0.1, length = 1.8, difficulty = "medium", image = "", imageFile = "surfboard.png" },
	{ id = "bathtub", name = "Bathtub", category = "Everyday", guess = "length", height = 0.55, length = 1.7, difficulty = "medium", image = "", imageFile = "bathtub.png" },
	{ id = "king_size_bed", name = "King Size Bed", category = "Everyday", guess = "length", height = 0.6, length = 2.03, difficulty = "medium", image = "", imageFile = "king_size_bed.png" },
	{ id = "wine_bottle", name = "Wine Bottle", category = "Everyday", guess = "height", height = 0.3, length = 0.076, difficulty = "easy", image = "", imageFile = "wine_bottle.png" },
	{ id = "soda_can", name = "Soda Can", category = "Everyday", guess = "height", height = 0.122, length = 0.066, difficulty = "easy", image = "", imageFile = "soda_can.png" },
	{ id = "computer_keyboard", name = "Computer Keyboard", category = "Everyday", guess = "length", height = 0.03, length = 0.44, difficulty = "medium", image = "", imageFile = "computer_keyboard.png" },
	{ id = "tennis_racket", name = "Tennis Racket", category = "Everyday", guess = "length", height = 0.27, length = 0.685, difficulty = "medium", image = "", imageFile = "tennis_racket.png" },
	{ id = "bowling_pin", name = "Bowling Pin", category = "Everyday", guess = "height", height = 0.381, length = 0.121, difficulty = "medium", image = "", imageFile = "bowling_pin.png" },

	{ id = "banana", name = "Banana", category = "Food", guess = "length", height = 0.04, length = 0.19, difficulty = "easy", image = "", imageFile = "banana.png" },
	{ id = "apple", name = "Apple", category = "Food", guess = "height", height = 0.08, length = 0.08, difficulty = "easy", image = "", imageFile = "apple.png" },
	{ id = "watermelon", name = "Watermelon", category = "Food", guess = "length", height = 0.25, length = 0.4, difficulty = "medium", image = "", imageFile = "watermelon.png" },
	{ id = "pineapple", name = "Pineapple", category = "Food", guess = "height", height = 0.4, length = 0.15, difficulty = "medium", image = "", imageFile = "pineapple.png" },
	{ id = "strawberry", name = "Strawberry", category = "Food", guess = "height", height = 0.035, length = 0.03, difficulty = "medium", image = "", imageFile = "strawberry.png" },
	{ id = "chicken_egg", name = "Chicken Egg", category = "Food", guess = "height", height = 0.057, length = 0.043, difficulty = "easy", image = "", imageFile = "chicken_egg.png" },
	{ id = "large_pizza", name = "Large Pizza", category = "Food", guess = "length", height = 0.03, length = 0.36, difficulty = "easy", image = "", imageFile = "large_pizza.png" },
	{ id = "baguette", name = "Baguette", category = "Food", guess = "length", height = 0.06, length = 0.65, difficulty = "medium", image = "", imageFile = "baguette.png" },
	{ id = "hot_dog", name = "Hot Dog", category = "Food", guess = "length", height = 0.05, length = 0.15, difficulty = "medium", image = "", imageFile = "hot_dog.png" },
	{ id = "coconut", name = "Coconut", category = "Food", guess = "height", height = 0.25, length = 0.2, difficulty = "medium", image = "", imageFile = "coconut.png" },
	{ id = "grain_of_rice", name = "Grain of Rice", category = "Food", guess = "length", height = 0.002, length = 0.006, difficulty = "hard", image = "", imageFile = "grain_of_rice.png" },
	{ id = "pumpkin", name = "Pumpkin", category = "Food", guess = "height", height = 0.3, length = 0.35, difficulty = "easy", image = "", imageFile = "pumpkin.png" },

	{ id = "ant", name = "Ant", category = "Animals", guess = "length", height = 0.002, length = 0.005, difficulty = "medium", image = "", imageFile = "ant.png" },
	{ id = "honeybee", name = "Honeybee", category = "Animals", guess = "length", height = 0.006, length = 0.013, difficulty = "medium", image = "", imageFile = "honeybee.png" },
	{ id = "ladybug", name = "Ladybug", category = "Animals", guess = "length", height = 0.004, length = 0.007, difficulty = "medium", image = "", imageFile = "ladybug.png" },
	{ id = "monarch_butterfly", name = "Monarch Butterfly", category = "Animals", guess = "length", height = 0.07, length = 0.1, difficulty = "medium", image = "", imageFile = "monarch_butterfly.png" },
	{ id = "hummingbird", name = "Hummingbird", category = "Animals", guess = "length", height = 0.04, length = 0.08, difficulty = "hard", image = "", imageFile = "hummingbird.png" },
	{ id = "house_mouse", name = "House Mouse", category = "Animals", guess = "length", height = 0.04, length = 0.17, difficulty = "medium", image = "", imageFile = "house_mouse.png" },
	{ id = "hamster", name = "Hamster", category = "Animals", guess = "length", height = 0.07, length = 0.15, difficulty = "medium", image = "", imageFile = "hamster.png" },
	{ id = "chicken", name = "Chicken", category = "Animals", guess = "height", height = 0.4, length = 0.4, difficulty = "easy", image = "", imageFile = "chicken.png" },
	{ id = "house_cat", name = "House Cat", category = "Animals", guess = "height", height = 0.3, length = 0.7, difficulty = "easy", image = "", imageFile = "house_cat.png" },
	{ id = "chihuahua", name = "Chihuahua", category = "Animals", guess = "height", height = 0.25, length = 0.35, difficulty = "medium", image = "", imageFile = "chihuahua.png" },
	{ id = "labrador_retriever", name = "Labrador Retriever", category = "Animals", guess = "height", height = 0.8, length = 1.1, difficulty = "easy", image = "", imageFile = "labrador_retriever.png" },
	{ id = "emperor_penguin", name = "Emperor Penguin", category = "Animals", guess = "height", height = 1.15, length = 0.5, difficulty = "medium", image = "", imageFile = "emperor_penguin.png" },
	{ id = "ostrich", name = "Ostrich", category = "Animals", guess = "height", height = 2.5, length = 1.8, difficulty = "medium", image = "", imageFile = "ostrich.png" },
	{ id = "red_kangaroo", name = "Red Kangaroo", category = "Animals", guess = "height", height = 1.6, length = 1.8, difficulty = "medium", image = "", imageFile = "red_kangaroo.png" },
	{ id = "horse", name = "Horse", category = "Animals", guess = "height", height = 2.3, length = 2.4, difficulty = "medium", image = "", imageFile = "horse.png" },
	{ id = "cow", name = "Cow", category = "Animals", guess = "height", height = 1.5, length = 2.5, difficulty = "medium", image = "", imageFile = "cow.png" },
	{ id = "grizzly_bear_standing", name = "Grizzly Bear (standing)", category = "Animals", guess = "height", height = 2.4, length = 0.9, difficulty = "medium", image = "", imageFile = "grizzly_bear_standing.png" },
	{ id = "gorilla_standing", name = "Gorilla (standing)", category = "Animals", guess = "height", height = 1.7, length = 0.8, difficulty = "medium", image = "", imageFile = "gorilla_standing.png" },
	{ id = "giraffe", name = "Giraffe", category = "Animals", guess = "height", height = 5.5, length = 4, difficulty = "medium", image = "", imageFile = "giraffe.png" },
	{ id = "african_elephant", name = "African Elephant", category = "Animals", guess = "height", height = 3.4, length = 6.5, difficulty = "medium", image = "", imageFile = "african_elephant.png" },
	{ id = "hippopotamus", name = "Hippopotamus", category = "Animals", guess = "length", height = 1.5, length = 4, difficulty = "hard", image = "", imageFile = "hippopotamus.png" },
	{ id = "white_rhinoceros", name = "White Rhinoceros", category = "Animals", guess = "length", height = 1.8, length = 4, difficulty = "hard", image = "", imageFile = "white_rhinoceros.png" },
	{ id = "grevys_zebra", name = "Grevy's Zebra", category = "Animals", guess = "length", height = 1.9, length = 2.7, difficulty = "medium", image = "", imageFile = "grevys_zebra.png" },
	{ id = "saltwater_crocodile", name = "Saltwater Crocodile", category = "Animals", guess = "length", height = 0.5, length = 5, difficulty = "hard", image = "", imageFile = "saltwater_crocodile.png" },
	{ id = "reticulated_python", name = "Reticulated Python", category = "Animals", guess = "length", height = 0.2, length = 6, difficulty = "hard", image = "", imageFile = "reticulated_python.png" },
	{ id = "great_white_shark", name = "Great White Shark", category = "Animals", guess = "length", height = 1.5, length = 4.5, difficulty = "medium", image = "", imageFile = "great_white_shark.png" },
	{ id = "orca", name = "Orca", category = "Animals", guess = "length", height = 2.8, length = 7.5, difficulty = "medium", image = "", imageFile = "orca.png" },
	{ id = "blue_whale", name = "Blue Whale", category = "Animals", guess = "length", height = 4.5, length = 25, difficulty = "medium", image = "", imageFile = "blue_whale.png" },
	{ id = "japanese_spider_crab", name = "Japanese Spider Crab", category = "Animals", guess = "length", height = 0.8, length = 3, difficulty = "hard", image = "", imageFile = "japanese_spider_crab.png" },
	{ id = "giant_squid", name = "Giant Squid", category = "Animals", guess = "length", height = 1, length = 12, difficulty = "hard", image = "", imageFile = "giant_squid.png" },
	{ id = "bald_eagle_wingspan", name = "Bald Eagle (wingspan)", category = "Animals", guess = "length", height = 0.8, length = 2, difficulty = "medium", image = "", imageFile = "bald_eagle_wingspan.png" },
	{ id = "flamingo", name = "Flamingo", category = "Animals", guess = "height", height = 1.4, length = 0.8, difficulty = "medium", image = "", imageFile = "flamingo.png" },
	{ id = "moose", name = "Moose", category = "Animals", guess = "height", height = 2.5, length = 3, difficulty = "hard", image = "", imageFile = "moose.png" },
	{ id = "dromedary_camel", name = "Dromedary Camel", category = "Animals", guess = "height", height = 2.2, length = 3, difficulty = "medium", image = "", imageFile = "dromedary_camel.png" },
	{ id = "bengal_tiger", name = "Bengal Tiger", category = "Animals", guess = "length", height = 1.1, length = 3, difficulty = "hard", image = "", imageFile = "bengal_tiger.png" },
	{ id = "polar_bear", name = "Polar Bear", category = "Animals", guess = "length", height = 1.5, length = 2.5, difficulty = "medium", image = "", imageFile = "polar_bear.png" },
	{ id = "komodo_dragon", name = "Komodo Dragon", category = "Animals", guess = "length", height = 0.4, length = 2.6, difficulty = "hard", image = "", imageFile = "komodo_dragon.png" },

	{ id = "tyrannosaurus_rex", name = "Tyrannosaurus Rex", category = "Dinosaurs", guess = "length", height = 4, length = 12.3, difficulty = "medium", image = "", imageFile = "tyrannosaurus_rex.png" },
	{ id = "triceratops", name = "Triceratops", category = "Dinosaurs", guess = "length", height = 3, length = 9, difficulty = "hard", image = "", imageFile = "triceratops.png" },
	{ id = "stegosaurus", name = "Stegosaurus", category = "Dinosaurs", guess = "length", height = 4, length = 9, difficulty = "hard", image = "", imageFile = "stegosaurus.png" },
	{ id = "velociraptor", name = "Velociraptor", category = "Dinosaurs", guess = "length", height = 0.5, length = 2, difficulty = "medium", image = "", imageFile = "velociraptor.png" },
	{ id = "brachiosaurus", name = "Brachiosaurus", category = "Dinosaurs", guess = "height", height = 12.5, length = 22, difficulty = "hard", image = "", imageFile = "brachiosaurus.png" },
	{ id = "argentinosaurus", name = "Argentinosaurus", category = "Dinosaurs", guess = "length", height = 8, length = 35, difficulty = "hard", image = "", imageFile = "argentinosaurus.png" },
	{ id = "woolly_mammoth", name = "Woolly Mammoth", category = "Dinosaurs", guess = "height", height = 3.3, length = 5, difficulty = "medium", image = "", imageFile = "woolly_mammoth.png" },
	{ id = "pteranodon_wingspan", name = "Pteranodon (wingspan)", category = "Dinosaurs", guess = "length", height = 1.8, length = 6, difficulty = "hard", image = "", imageFile = "pteranodon_wingspan.png" },
	{ id = "megalodon", name = "Megalodon", category = "Dinosaurs", guess = "length", height = 4, length = 15, difficulty = "hard", image = "", imageFile = "megalodon.png" },
	{ id = "spinosaurus", name = "Spinosaurus", category = "Dinosaurs", guess = "length", height = 5, length = 14, difficulty = "hard", image = "", imageFile = "spinosaurus.png" },

	{ id = "motorcycle", name = "Motorcycle", category = "Transport", guess = "length", height = 1.1, length = 2.1, difficulty = "medium", image = "", imageFile = "motorcycle.png" },
	{ id = "pickup_truck", name = "Pickup Truck", category = "Transport", guess = "length", height = 1.95, length = 5.9, difficulty = "medium", image = "", imageFile = "pickup_truck.png" },
	{ id = "double_decker_bus", name = "Double-Decker Bus", category = "Transport", guess = "height", height = 4.4, length = 11.2, difficulty = "medium", image = "", imageFile = "double_decker_bus.png" },
	{ id = "semi_truck_with_trailer", name = "Semi Truck with Trailer", category = "Transport", guess = "length", height = 4.1, length = 21, difficulty = "hard", image = "", imageFile = "semi_truck_with_trailer.png" },
	{ id = "m1_abrams_tank", name = "M1 Abrams Tank", category = "Transport", guess = "length", height = 2.4, length = 9.8, difficulty = "hard", image = "", imageFile = "m1_abrams_tank.png" },
	{ id = "hot_air_balloon", name = "Hot Air Balloon", category = "Transport", guess = "height", height = 25, length = 18, difficulty = "hard", image = "", imageFile = "hot_air_balloon.png" },
	{ id = "cessna_172", name = "Cessna 172", category = "Transport", guess = "length", height = 2.7, length = 8.3, difficulty = "hard", image = "", imageFile = "cessna_172.png" },
	{ id = "boeing_747", name = "Boeing 747", category = "Transport", guess = "length", height = 19.4, length = 70.7, difficulty = "medium", image = "", imageFile = "boeing_747.png" },
	{ id = "airbus_a380", name = "Airbus A380", category = "Transport", guess = "length", height = 24.1, length = 72.7, difficulty = "medium", image = "", imageFile = "airbus_a380.png" },
	{ id = "space_shuttle", name = "Space Shuttle", category = "Transport", guess = "length", height = 17.3, length = 37.2, difficulty = "hard", image = "", imageFile = "space_shuttle.png" },
	{ id = "saturn_v_rocket", name = "Saturn V Rocket", category = "Transport", guess = "height", height = 110.6, length = 10.1, difficulty = "hard", image = "", imageFile = "saturn_v_rocket.png" },
	{ id = "falcon_9_rocket", name = "Falcon 9 Rocket", category = "Transport", guess = "height", height = 70, length = 3.7, difficulty = "hard", image = "", imageFile = "falcon_9_rocket.png" },
	{ id = "titanic", name = "Titanic", category = "Transport", guess = "length", height = 53, length = 269, difficulty = "medium", image = "", imageFile = "titanic.png" },
	{ id = "nimitz_aircraft_carrier", name = "Nimitz Aircraft Carrier", category = "Transport", guess = "length", height = 60, length = 333, difficulty = "hard", image = "", imageFile = "nimitz_aircraft_carrier.png" },
	{ id = "largest_container_ship", name = "Largest Container Ship", category = "Transport", guess = "length", height = 70, length = 400, difficulty = "hard", image = "", imageFile = "largest_container_ship.png" },
	{ id = "ohio_class_submarine", name = "Ohio-Class Submarine", category = "Transport", guess = "length", height = 12, length = 170, difficulty = "hard", image = "", imageFile = "ohio_class_submarine.png" },
	{ id = "icon_of_the_seas_cruise_ship", name = "Icon of the Seas Cruise Ship", category = "Transport", guess = "length", height = 70, length = 365, difficulty = "hard", image = "", imageFile = "icon_of_the_seas_cruise_ship.png" },
	{ id = "canoe", name = "Canoe", category = "Transport", guess = "length", height = 0.4, length = 5, difficulty = "medium", image = "", imageFile = "canoe.png" },
	{ id = "venetian_gondola", name = "Venetian Gondola", category = "Transport", guess = "length", height = 1.5, length = 11, difficulty = "hard", image = "", imageFile = "venetian_gondola.png" },
	{ id = "subway_car", name = "Subway Car", category = "Transport", guess = "length", height = 3.7, length = 18, difficulty = "medium", image = "", imageFile = "subway_car.png" },
	{ id = "formula_1_car", name = "Formula 1 Car", category = "Transport", guess = "length", height = 0.95, length = 5.6, difficulty = "medium", image = "", imageFile = "formula_1_car.png" },
	{ id = "monster_truck", name = "Monster Truck", category = "Transport", guess = "height", height = 3.5, length = 5.5, difficulty = "medium", image = "", imageFile = "monster_truck.png" },

	{ id = "great_pyramid_of_giza", name = "Great Pyramid of Giza", category = "Buildings", guess = "height", height = 139, length = 230, difficulty = "medium", image = "", imageFile = "great_pyramid_of_giza.png" },
	{ id = "burj_khalifa", name = "Burj Khalifa", category = "Buildings", guess = "height", height = 828, length = 150, difficulty = "medium", image = "", imageFile = "burj_khalifa.png" },
	{ id = "empire_state_building", name = "Empire State Building", category = "Buildings", guess = "height", height = 443, length = 130, difficulty = "medium", image = "", imageFile = "empire_state_building.png" },
	{ id = "big_ben", name = "Big Ben", category = "Buildings", guess = "height", height = 96, length = 12, difficulty = "medium", image = "", imageFile = "big_ben.png" },
	{ id = "leaning_tower_of_pisa", name = "Leaning Tower of Pisa", category = "Buildings", guess = "height", height = 56, length = 20, difficulty = "medium", image = "", imageFile = "leaning_tower_of_pisa.png" },
	{ id = "christ_the_redeemer_with_pedestal", name = "Christ the Redeemer (with pedestal)", category = "Buildings", guess = "height", height = 38, length = 28, difficulty = "hard", image = "", imageFile = "christ_the_redeemer_with_pedestal.png" },
	{ id = "colosseum", name = "Colosseum", category = "Buildings", guess = "height", height = 48, length = 189, difficulty = "hard", image = "", imageFile = "colosseum.png" },
	{ id = "taj_mahal", name = "Taj Mahal", category = "Buildings", guess = "height", height = 73, length = 95, difficulty = "hard", image = "", imageFile = "taj_mahal.png" },
	{ id = "sydney_opera_house", name = "Sydney Opera House", category = "Buildings", guess = "height", height = 65, length = 183, difficulty = "hard", image = "", imageFile = "sydney_opera_house.png" },
	{ id = "golden_gate_bridge_tower_height", name = "Golden Gate Bridge (tower height)", category = "Buildings", guess = "height", height = 227, length = 2737, difficulty = "hard", image = "", imageFile = "golden_gate_bridge_tower_height.png" },
	{ id = "tower_bridge", name = "Tower Bridge", category = "Buildings", guess = "height", height = 65, length = 244, difficulty = "hard", image = "", imageFile = "tower_bridge.png" },
	{ id = "cn_tower", name = "CN Tower", category = "Buildings", guess = "height", height = 553, length = 60, difficulty = "medium", image = "", imageFile = "cn_tower.png" },
	{ id = "shanghai_tower", name = "Shanghai Tower", category = "Buildings", guess = "height", height = 632, length = 128, difficulty = "hard", image = "", imageFile = "shanghai_tower.png" },
	{ id = "petronas_towers", name = "Petronas Towers", category = "Buildings", guess = "height", height = 452, length = 110, difficulty = "hard", image = "", imageFile = "petronas_towers.png" },
	{ id = "one_world_trade_center", name = "One World Trade Center", category = "Buildings", guess = "height", height = 541, length = 61, difficulty = "hard", image = "", imageFile = "one_world_trade_center.png" },
	{ id = "tokyo_skytree", name = "Tokyo Skytree", category = "Buildings", guess = "height", height = 634, length = 68, difficulty = "hard", image = "", imageFile = "tokyo_skytree.png" },
	{ id = "space_needle", name = "Space Needle", category = "Buildings", guess = "height", height = 184, length = 42, difficulty = "hard", image = "", imageFile = "space_needle.png" },
	{ id = "gateway_arch", name = "Gateway Arch", category = "Buildings", guess = "height", height = 192, length = 192, difficulty = "medium", image = "", imageFile = "gateway_arch.png" },
	{ id = "mount_rushmore_one_head", name = "Mount Rushmore (one head)", category = "Buildings", guess = "height", height = 18, length = 12, difficulty = "hard", image = "", imageFile = "mount_rushmore_one_head.png" },
	{ id = "great_sphinx_of_giza", name = "Great Sphinx of Giza", category = "Buildings", guess = "length", height = 20, length = 73, difficulty = "hard", image = "", imageFile = "great_sphinx_of_giza.png" },
	{ id = "london_eye", name = "London Eye", category = "Buildings", guess = "height", height = 135, length = 120, difficulty = "medium", image = "", imageFile = "london_eye.png" },
	{ id = "pont_du_gard", name = "Pont du Gard", category = "Buildings", guess = "height", height = 49, length = 275, difficulty = "hard", image = "", imageFile = "pont_du_gard.png" },
	{ id = "moai_statue", name = "Moai Statue", category = "Buildings", guess = "height", height = 4, length = 1.6, difficulty = "hard", image = "", imageFile = "moai_statue.png" },
	{ id = "hollywood_sign", name = "Hollywood Sign", category = "Buildings", guess = "height", height = 13.7, length = 107, difficulty = "hard", image = "", imageFile = "hollywood_sign.png" },

	{ id = "mount_everest", name = "Mount Everest", category = "Nature", guess = "height", height = 8849, length = 20000, difficulty = "medium", image = "", imageFile = "mount_everest.png" },
	{ id = "mount_fuji", name = "Mount Fuji", category = "Nature", guess = "height", height = 3776, length = 35000, difficulty = "hard", image = "", imageFile = "mount_fuji.png" },
	{ id = "mount_kilimanjaro", name = "Mount Kilimanjaro", category = "Nature", guess = "height", height = 5895, length = 40000, difficulty = "hard", image = "", imageFile = "mount_kilimanjaro.png" },
	{ id = "angel_falls", name = "Angel Falls", category = "Nature", guess = "height", height = 979, length = 150, difficulty = "hard", image = "", imageFile = "angel_falls.png" },
	{ id = "niagara_falls_horseshoe", name = "Niagara Falls (Horseshoe)", category = "Nature", guess = "height", height = 51, length = 670, difficulty = "medium", image = "", imageFile = "niagara_falls_horseshoe.png" },
	{ id = "hyperion_tallest_tree", name = "Hyperion (tallest tree)", category = "Nature", guess = "height", height = 116, length = 30, difficulty = "hard", image = "", imageFile = "hyperion_tallest_tree.png" },
	{ id = "general_sherman_tree", name = "General Sherman Tree", category = "Nature", guess = "height", height = 84, length = 30, difficulty = "hard", image = "", imageFile = "general_sherman_tree.png" },
	{ id = "baobab_tree", name = "Baobab Tree", category = "Nature", guess = "height", height = 25, length = 20, difficulty = "hard", image = "", imageFile = "baobab_tree.png" },
	{ id = "sunflower", name = "Sunflower", category = "Nature", guess = "height", height = 3, length = 0.6, difficulty = "medium", image = "", imageFile = "sunflower.png" },
	{ id = "grand_canyon_depth", name = "Grand Canyon (depth)", category = "Nature", guess = "height", height = 1800, length = 16000, difficulty = "hard", image = "", imageFile = "grand_canyon_depth.png" },
	{ id = "old_faithful_geyser_eruption", name = "Old Faithful Geyser (eruption)", category = "Nature", guess = "height", height = 40, length = 10, difficulty = "hard", image = "", imageFile = "old_faithful_geyser_eruption.png" },
	{ id = "coconut_palm", name = "Coconut Palm", category = "Nature", guess = "height", height = 25, length = 8, difficulty = "medium", image = "", imageFile = "coconut_palm.png" },
	{ id = "saguaro_cactus", name = "Saguaro Cactus", category = "Nature", guess = "height", height = 12, length = 5, difficulty = "hard", image = "", imageFile = "saguaro_cactus.png" },
	{ id = "rafflesia_flower", name = "Rafflesia Flower", category = "Nature", guess = "length", height = 0.3, length = 1, difficulty = "hard", image = "", imageFile = "rafflesia_flower.png" },
	{ id = "giant_bamboo", name = "Giant Bamboo", category = "Nature", guess = "height", height = 30, length = 3, difficulty = "hard", image = "", imageFile = "giant_bamboo.png" },
}

return ObjectLibrary
